### ISSUE TITLE
Client ID is not used when re-starting a timer

### ISSUE THREAD

**Issue by anderssv** [pascalbe-dev/ulauncher-toggl#6]
If the previous task has a client_id, it should be restarted with the same.

**Comment by anderssv** [comment]
Sorry if I messed up referencing PR correctly. A bit new to the PR thing. :smile:

**Comment by pascalbe-dev** [comment]
Hey, no worries about the reference. 

From what I understand right now, your feature proposal makes total sense. 
Will check it out in more detail, maybe make a few refactorings and probably merge soon. Will keep you updated. 

Thanks for using the tool by and reaching our by the way 🥇

**Comment by pascalbe-dev** [comment]
Okay, I took a quick look.

I do not yet understand the problem, @anderssv . I can not see a way to create a time entry with a client directly assigned. I can only create assign clients to a time entry by using projects. And the project can be reused when starting a new time entry. 

So in short: 
The client ID should be indirectly assigned when you assign the project. Therefore, no explicit client assignment should be necessary.

@anderssv 
Do I miss something? Could you elaborate on which kind of issue you experience?

**Comment by anderssv** [comment]
You are absolutely right. Sorry about that. I should have re-verified the negative case after having a "fix" for it. It does associated correctly based on the project. Pretty sure it had the wrong client (missing) the first time around though, which I based a lot of assumptions of. Just ignore my PR. :smile: Sorry again.

**Comment by pascalbe-dev** [comment]
No worries. Thanks for clarification. Have a nice weekend!
